---
- hosts: all
  connection: local

  vars_files:
    - config.yml

  vars_prompt:
    - name: "mas_email"
      prompt: "App Store email"
    - name: "mas_password"
      prompt: "App Store password"

  roles:
    - role: geerlingguy.homebrew
      tags: ['homebrew']
    - role: geerlingguy.mas
      when: mas_installed_apps
      tags: ['mas']

  tasks:
    - import_tasks: tasks/dockitems.yml
      tags: ['macos']

    - import_tasks: tasks/macos.yml
      tags: ['macos']

    - import_tasks: tasks/workspace.yml
      tags: ['dev']

    - import_tasks: tasks/iterm.yml
      tags: ['dev']

    - import_tasks: tasks/vscode.yml
      tags: ['dev']

    - import_tasks: tasks/git-repos.yml
      tags: ['dev']
