---
- name: Ensure `/Code/User/` directory exists
  file:
    path: "~/Library/Application Support/Code/User/"
    state: directory

- name: Copy user settings
  copy:
    src: ../files/vscode/settings.json
    dest: ~/Library/Application Support/Code/User/settings.json
    backup: yes

- name: Create symbolic link to `code` bin
  file:
    src: /Applications/Visual Studio Code.app/Contents/Resources/app/bin/code
    dest: /usr/local/bin/code
    state: link

- name: Install vscode extensions
  shell: code --install-extension {{ item }}
  with_items: "{{ vscode_extensions }}"



